name: CI-Develop

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest
    env:
      REMOTE: ${{ github.event.pull_request.head.repo.clone_url }}
      ORIGEN: ${{ github.event.pull_request.head.ref }}
      DESTINO: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Re-run release last check
        if: github.event.pull_request.merged == true
        env:
          OWNER: JhonJimenezCastro
          REPO: testrepositor
          BRANCH: release
          TOKEN: ${{ secrets.TOKEN }}
        run: |
            echo "Procesando la rama: $BRANCH"
    
            runId=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $TOKEN" \
              https://api.github.com/repos/${OWNER}/${REPO}/actions/runs?branch=${BRANCH} | \
              jq '.workflow_runs[0].id' || echo '')
    
            if [ -z "$runId" ] || [ "$runId" == "null" ]
            then
              echo "No se encontraron runs para la rama $BRANCH"
            else
              curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer $TOKEN" \
                https://api.github.com/repos/${OWNER}/${REPO}/actions/runs/${runId}/rerun
            fi
