name: CI-Develop

on:
  push:
    branches:
      - develop

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - edited
    branches:
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
    
      - name: Crear Auto-PR
        if: github.event.pull_request.merged == true
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          DESTINO: "release"
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          set -e

          # Script mejorado
          echo -ne "\e[45m[INFO]\e[0m Auto-PR CREANDO PULL REQUEST para la rama release \e[0m\n"

          PR_RESPONSE=$(curl -s -u "${TOKEN}:" -X POST -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" \
              -d '{"title":"Auto-PR : '${ORIGEN}' to: '${DESTINO}'","body":"proceso generado por gitbot","head":"'${ORIGEN}'","base":"'${DESTINO}'"}')

          if ! echo "$PR_RESPONSE" | jq empty &> /dev/null; then
              echo -ne "\e[41m[ERROR]\e[0m La respuesta de GitHub no es un JSON válido.\e[0m\n"
              exit 1
          fi

          sleep 5s

          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

          if [[ -z "$PR_NUMBER" ]]; then
              echo -ne "\e[41m[ERROR]\e[0m Error al crear PR para la rama ${DESTINO}\e[0m\n"
              exit 1
          fi

          echo -ne "\e[42m[SUCCESS]\e[0m Pull Request creado exitosamente: ${PR_NUMBER}\e[0m\n"

      - name: Deploy
        if: github.event_name == 'push'
        run: |
             echo "deploying rama base con el shelltool"



          

