name: CI-Main

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - edited
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Run Tests
        run: |
              echo "run snyk sonar etc con el shelltool"

      - name: Validar que el PR ya pasó por ambiente previo
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REMOTE: ${{ github.event.pull_request.head.repo.clone_url }}
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          PREVIO_ENV: staging
        run: |
          git fetch origin ${PREVIO_ENV}
          LAST_COMMIT=$(git rev-parse origin/${ORIGEN})
    
          COMMON_ANCESTOR=$(git merge-base origin/${PREVIO_ENV} $LAST_COMMIT)
          if [ "$COMMON_ANCESTOR" != "$LAST_COMMIT" ]; then
            echo "Los cambios de la rama ${ORIGEN} deben haber sido integrados previamente en la rama ${PREVIO_ENV}"
            exit 1
          fi

      - name: Deploy
        if: github.event_name == 'push'
        run: |
             echo "deploying rama base con el shelltool"