name: CI-Staging

on:
  push:
    branches:
      - staging

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - edited
    branches:
      - staging

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Validar que el PR ya pasó por ambiente previo
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REMOTE: ${{ github.event.pull_request.head.repo.clone_url }}
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          PREVIO_ENV: release
        run: |
          git fetch origin ${PREVIO_ENV}
          LAST_COMMIT=$(git rev-parse origin/${ORIGEN})
    
          COMMON_ANCESTOR=$(git merge-base origin/${PREVIO_ENV} $LAST_COMMIT)
          if [ "$COMMON_ANCESTOR" != "$LAST_COMMIT" ]; then
            echo "Los cambios de la rama ${ORIGEN} deben haber sido integrados previamente en la rama ${PREVIO_ENV}"
            exit 1
          fi
    
      - name: Crear Auto-PR
        if: github.event.pull_request.merged == true
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          DESTINO: "main"
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          set -e

          # Script mejorado
          echo -ne "\e[45m[INFO]\e[0m Auto-PR CREANDO PULL REQUEST para la rama main \e[0m\n"

          PR_RESPONSE=$(curl -s -u "${TOKEN}:" -X POST -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" \
              -d '{"title":"Auto-PR : '${ORIGEN}' to: '${DESTINO}'","body":"proceso generado por gitbot","head":"'${ORIGEN}'","base":"'${DESTINO}'"}')

          if ! echo "$PR_RESPONSE" | jq empty &> /dev/null; then
              echo -ne "\e[41m[ERROR]\e[0m La respuesta de GitHub no es un JSON válido.\e[0m\n"
              exit 1
          fi

          sleep 5s

          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

          if [[ -z "$PR_NUMBER" ]]; then
              echo -ne "\e[41m[ERROR]\e[0m Error al crear PR para la rama ${DESTINO}\e[0m\n"
              exit 1
          fi

          echo -ne "\e[42m[SUCCESS]\e[0m Pull Request creado exitosamente: ${PR_NUMBER}\e[0m\n"

      - name: Deploy
        if: github.event_name == 'push'
        run: |
             echo "deploying rama base con el shelltool"